

var IMAGE_TILES = new Array();
var img_0 = 'images/0.png';
var img_1 = 'images/1.png';
var img_2 = 'images/2.png';
var img_3 = 'images/3.png';
var img_4 = 'images/4.png';
var img_5 = 'images/5.png';
var img_6 = 'images/6.png';
var img_7 = 'images/7.png';
var img_8 = 'images/8.png';
var RAND_2D_ARRAY = new Array();
var TILE_SIZE = 60; //the size is in pixels
var MAX_NUM_ALLOWED = 8;
var LEVEL = "LEVEL1";
var GAME_TYPE = "SINGLE_PLAYER";
var MATRIX_SIZE = 4; //This determines the size of the matrix. This can be set by the function setParametes
var MATRIX = new Array();
var BLUE = null;
var RED = null;
var GREEN = null;
var NO_COLOR = null;
var GAME_ARENA = 'MainGame.html';
var TILE_SPACING = 2; //the size is in pixels
var FRAME_TO_ADD_TILES = "tilePlane"; //frame where all tiles are added.
var color_original_1 = 'blue';
var color_original_2 = 'white';
var color_clicked = 'green';
var color_invalid_addition = 'yellow';
var color_valid_addition = 'brown';
var COLOR_TILES = new Array();	
var COLOR_RESTORE = 0;
var COLOR_CLICK = 2;
var COLOR_INVALID_ADDITION = 3;
var COLOR_VALID_ADDITION = 4;
var MAX_FREQ_7_AND_8_LEVEL_1 = 0.7;
var MAX_FREQ_0_AND_1_LEVEL_2 = 0.5;
var MAX_FREQ_0_AND_1_LEVEL_3 = 0.45;
var MAX_FREQ_0 = 0.1;
var NO_OF_DIRECTIONS = 8;
var TRIES_GET_NUMBER_IN_MATRIX_LIMIT = 20;
var BREAKS_MIN_LIMIT = 7;